const app=document.querySelector('#app'),toast=document.querySelector('#toast');
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const p=await r.json();if(!p.ok)throw new Error(p.violation?.factualBasis||p.message||p.error);return p.data}
function notice(message,bad=false){toast.textContent=message;toast.style.background=bad?'#8b3033':'#176a45';toast.style.display='block';setTimeout(()=>toast.style.display='none',3000)}
const fmt=d=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'long'}).format(new Date(`${d}T00:00:00Z`));
const empty=text=>`<div class="card muted">${esc(text)}</div>`;
function bindLinks(){document.querySelectorAll('a[href^="/"]').forEach(a=>a.onclick=e=>{if(a.origin===location.origin){e.preventDefault();history.pushState({},'',a.pathname);render()}});document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',location.pathname===a.dataset.path))}
function busy(button,run){const old=button.textContent;button.disabled=true;button.textContent='처리 중…';return run().finally(()=>{button.disabled=false;button.textContent=old})}
async function dashboard(){const w=await api('/api/world');document.querySelector('#storage').textContent=w.storage==='REDIS_REST_PERSISTENT'?'영구 저장소 연결됨':'임시 로컬 저장소';app.innerHTML=`<section class="hero"><div><div class="muted">현재 세계 날짜</div><div class="date">${fmt(w.date)}</div><div class="muted">시드 ${w.seed} · ${w.scenario}</div></div></section>
<div class="grid"><div class="card"><strong>진행 중인 대회</strong><b>${esc(w.activeCompetitions.join(', ')||'없음')}</b></div><div class="card"><strong>다음 이벤트</strong><b>${esc(w.nextEvent?.kind||'없음')}</b><div>${esc(w.nextEvent?.date||'')}</div></div><div class="card"><strong>대표팀 / 대회</strong><b>${w.teamCount} / ${w.competitionCount}</b></div><a class="card" href="/audit"><strong>감사 오류</strong><b>${w.auditErrorCount}</b></a></div>
<h2 class="section-title">시간 진행</h2><div class="actions">${[['DAY','하루 진행'],['WEEK','일주일 진행'],['MONTH','한 달 진행'],['NEXT_EVENT','다음 이벤트'],['YEAR','1년 진행']].map(([m,t])=>`<button data-advance="${m}" class="${m==='NEXT_EVENT'?'primary':''}">${t}</button>`).join('')}<button id="save">저장</button><button id="load">불러오기</button><a class="button" href="/settings">새 세계 생성</a><button class="danger" id="reset">세계 초기화</button></div>
<h2 class="section-title">최근 경기</h2><div class="list">${w.recentMatches.length?w.recentMatches.map(matchRow).join(''):empty('아직 진행된 경기가 없습니다. 다음 이벤트를 진행하세요.')}</div>`;
document.querySelectorAll('[data-advance]').forEach(b=>b.onclick=()=>busy(b,async()=>{await api('/api/world/advance',{method:'POST',body:JSON.stringify({mode:b.dataset.advance,amount:1})});notice('세계 시간이 진행되었습니다.');await dashboard()}));
document.querySelector('#save').onclick=e=>busy(e.target,async()=>{const d=await api('/api/save',{method:'POST'});notice(`${d.savedAtWorldDate} 상태를 실제 저장했습니다.`)});
document.querySelector('#load').onclick=e=>busy(e.target,async()=>{await api('/api/load',{method:'POST'});notice('저장 세계를 복원했습니다.');await dashboard()});
document.querySelector('#reset').onclick=e=>{if(confirm('같은 시드로 현재 세계를 완전히 초기화할까요?'))busy(e.target,async()=>{await api('/api/world/new',{method:'POST',body:JSON.stringify({seed:w.seed,scenario:w.scenario})});notice('세계를 초기 상태로 되돌렸습니다.');await dashboard()})};bindLinks()}
function matchRow(m){return `<a class="row" href="/matches"><b>${esc(m.home)} ${m.winner===m.home?'승':'패'} · ${esc(m.away)} ${m.winner===m.away?'승':'패'}</b><br><span>${esc(m.date)} · ${esc(m.edition_id)} · 예상 ${m.expected?Math.round(m.expected[m.home]*100)+'%':'—'} · Δ ${m.rating_delta?Number(m.rating_delta[m.home]).toFixed(2):'—'}</span></a>`}
async function teams(){const d=await api('/api/teams');app.innerHTML=`<h1>국가대표팀</h1><div class="list">${d.map(x=>`<a class="row" href="/teams/${x.id}"><b>${esc(x.name)}</b> · ${x.id}<br><span>${x.confederation} · 레이팅 ${x.rating.toFixed(2)} · 명성 ${x.reputation.toFixed(1)}</span></a>`).join('')}</div>`;bindLinks()}
async function team(id){const x=await api(`/api/teams/${encodeURIComponent(id)}`);app.innerHTML=`<h1>${esc(x.name)} <span class="muted">${x.id}</span></h1><div class="grid">${[['레이팅',x.rating.toFixed(2)],['공격/수비',`${x.attack}/${x.defence}`],['골키퍼',x.goalkeeping],['경험',x.experience.toFixed(1)],['문화',x.footballCulture],['인프라',x.infrastructure]].map(([a,b])=>`<div class="card"><strong>${a}</strong><b>${b}</b></div>`).join('')}</div><h2>경기</h2><div class="list">${x.matches.length?x.matches.map(matchRow).join(''):empty('경기 기록이 없습니다.')}</div>`;bindLinks()}
async function competitions(){const d=await api('/api/competitions');app.innerHTML=`<h1>대회 회차</h1><div class="list">${d.map(x=>`<a class="row" href="/competitions/${x.id}"><b>${x.id}</b> · ${x.year}<br><span>${x.completed?'완료':'예정/진행'} · 우승 ${esc(x.championId)}</span></a>`).join('')}</div>`;bindLinks()}
async function competition(id){const x=await api(`/api/competitions/${encodeURIComponent(id)}`);app.innerHTML=`<h1>${x.id}</h1><div class="grid"><div class="card"><strong>상태</strong><b>${x.completed?'완료':'진행 전/진행'}</b></div><div class="card"><strong>우승</strong><b>${esc(x.championId)}</b></div><div class="card"><strong>본선 참가</strong><b>${esc(x.finalists.join(', ')||'미확정')}</b></div></div><h2>진출 근거</h2><pre class="card">${esc(JSON.stringify({applications:x.applications,qualifiers:x.qualifiers},null,2))}</pre><h2>경기</h2><div class="list">${x.matches.length?x.matches.map(matchRow).join(''):empty('아직 경기가 없습니다.')}</div>`;bindLinks()}
async function matches(){const d=await api('/api/matches');app.innerHTML=`<h1>전체 경기 기록</h1><div class="list">${d.length?d.slice().reverse().map(m=>`<div class="row"><b>${m.home} vs ${m.away} — ${m.winner} 승</b><br><span>${m.date} · ${m.edition_id} · 중립 ${m.neutral?'예':'아니오'}</span><pre>${esc(JSON.stringify({preRating:m.pre_rating,modifiers:m.modifiers,expected:m.expected,ratingDelta:m.rating_delta,postRating:m.post_rating,rngDomain:m.rng_domain,basis:m.basis},null,2))}</pre></div>`).join(''):empty('아직 경기 기록이 없습니다.')}</div>`}
async function timeline(){const d=await api('/api/timeline');app.innerHTML=`<h1>세계 연대기</h1><div class="list">${d.length?d.map(x=>`<div class="row"><b>${esc(x.kind)}</b> <span>${esc(x.date)} ${x.future?'· 예정':''}</span><br>${esc(x.reason||'')}<br><span>${esc(x.basis||JSON.stringify(x.payload||{}))}</span></div>`).join(''):empty('기록된 사건이 없습니다.')}</div>`}
async function audit(){const d=await api('/api/audit');app.innerHTML=`<h1>정합성 감사</h1>${d.length?`<div class="list">${d.map(x=>`<pre class="row">${esc(JSON.stringify(x,null,2))}</pre>`).join('')}</div>`:empty('현재 TimelineAuditor가 발견한 오류가 없습니다.')}`}
async function settings(){const w=await api('/api/world');app.innerHTML=`<h1>새 세계 / 설정</h1><form id="new"><label>세계 시드<input name="seed" type="number" value="${w.seed}" required></label><label>테스트 시나리오<select name="scenario"><option value="EGYPT_1934">1934 이집트 우승 수직 슬라이스</option></select></label><label>이변 수준<select disabled><option>중간 (MVP 고정)</option></select></label><button class="button danger" type="submit">현재 세계 초기화 후 새 세계 생성</button></form><p class="muted">이 작업은 현재 진행 상태를 덮어씁니다. 먼저 저장 버튼으로 수동 저장할 수 있습니다.</p>`;document.querySelector('#new').onsubmit=async e=>{e.preventDefault();if(!confirm('현재 세계를 초기화할까요?'))return;const b=e.submitter;await busy(b,async()=>{await api('/api/world/new',{method:'POST',body:JSON.stringify({seed:Number(e.target.seed.value),scenario:e.target.scenario.value})});notice('새 테스트 세계를 생성했습니다.');history.pushState({},'','/');await render()})}}
async function render(){app.innerHTML='<div class="loading">불러오는 중…</div>';try{const p=location.pathname;if(p==='/')await dashboard();else if(p==='/teams')await teams();else if(p.startsWith('/teams/'))await team(decodeURIComponent(p.split('/')[2]));else if(p==='/competitions')await competitions();else if(p.startsWith('/competitions/'))await competition(decodeURIComponent(p.split('/')[2]));else if(p==='/matches')await matches();else if(p==='/timeline')await timeline();else if(p==='/audit')await audit();else if(p==='/settings')await settings();bindLinks()}catch(e){app.innerHTML=`<div class="card"><h2>오류</h2><p>${esc(e.message)}</p><button class="button" onclick="location.reload()">다시 시도</button></div>`;notice(e.message,true)}}
addEventListener('popstate',render);render();
